n = int(input('quantos números da sequencia de fibonacci deseja ver? '))
t1 = 0
t2 = 1
count = 3
print('{} -> {} '.format(t1, t2,), end='')
while count <= n:
    t3 = t1 + t2
    t1 = t2
    t2 = t3
    count += 1
    print('-> {}'.format(t3), end='')
